"""
LaunchFiles Package - Execution Scripts

This package contains scripts for launching experiments and executing the full pipeline.

Modules:
    - Execution scripts for various experimental configurations
    - Pre-trained model files (.h5)
    - Output directories for generated images and results

Typical Usage:
    python Mitigated/launch.py  # Main entry point for mitigated model experiments

Generated Outputs:
    - GeneratedImages/: Synthetic images generated by diffusion models
    - Model checkpoints and weights
    - Result statistics and confusion matrices
"""
